sudo: true
language: node_js
node_js:
- '12'
branches:
  only:
  - main
cache:
  directories:
  - node_modules
before_install:
- cd PartnerMeServer
- npm update
install:
- npm install
script:
# - npm test
- npm test unit/authtest.spec.js unit/matchtest.spec.js unit/messagetest.spec.js unit/userstest.spec.js --coverage
